//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VETAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long AppointmentId { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public System.DateTime AppointmentEndDate { get; set; }
        public long PatientId { get; set; }
        public long UserId { get; set; }
        public string ProblemDescription { get; set; }
        public bool Approved { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual User User { get; set; }
    }
}
