//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VETAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecord
    {
        public long RecordId { get; set; }
        public long PatientId { get; set; }
        public Nullable<long> MedicationId { get; set; }
        public int Diagnosis { get; set; }
        public string TreatmentDescription { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Medication Medication { get; set; }
    }
}
